2024-04-21 15:58:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F511F26E00>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-04-21 15:58:14 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F511F276A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-04-21 15:58:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F511F27E80>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-04-21 15:58:28 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F511F27730>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-04-21 15:58:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F511F27490>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-04-21 15:58:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F511F26F20>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-04-21 15:58:49 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F511F269B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-04-21 15:58:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F511F25870>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-04-21 15:59:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F2719EAFE0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-04-21 15:59:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F2719EBA90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-04-21 15:59:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F511F25150>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-04-21 15:59:24 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F511F26E30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-04-21 15:59:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F511F27400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-04-21 15:59:38 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F511F27BE0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-04-21 15:59:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F2719EBF10>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-04-21 15:59:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F511F27BE0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-04-21 16:00:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F511F27400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-04-21 16:00:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F511F26E30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
